TrajectoryPlannerROS:
    #Robot Configuration Parameters
    acc_lim_theta: 1.57
    acc_lim_x: 2
    acc_lim_y: 2

    max_vel_x: 1.0
    min_vel_x: 0.1
    max_vel_theta: 1.0
    min_in_place_vel_theta: 0.4
    backup_vel: -0.05
    escape_vel: -0.05
    holonomic_robot: true
    y_vels: [-0.3, -0.1, 0.1, 0.3]  #only used if holonomic robot is true

    global_frame_id: world