#robot footprint shape
#footprint: [[0.3, 0.3],[0.3, 0.3], [0.3, 0.3], [0.3, 0.3]]
robot_radius:  0.2

#plugins layers list
static_layer:
    enabled: true
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    map_topic: /projected_map
    first_map_only: false  # Only subscribe to the first message on the map topic
    subscribe_to_updates: true  #default: false
    track_unknown_space: true
    use_maximum: false
    trinary_costmap: true

obstacle_layer:
    enabled: true
    # Sensor management parameters
    observation_sources:     laser_scan_sensor  #  laser_scan_sensor  point_cloud_sensor
    laser_scan_sensor:
        # topic: /camrea/depth/color/points
        topic: /scan
        sensor_frame: laser_link
        # sensor_frame: camera_color_optical_frame
        observation_persistence: 0.0  # How long to keep each sensor reading in seconds.
        expected_update_rate: 0.5  # How often to expect a reading from a sensor in seconds.
        data_type: LaserScan #alternatives: LaserScan, Pointcloud, PointCloud2
        #data_type: PointCloud2 #alternatives: LaserScan, Pointcloud, PointCloud2
        clearing: true #true, modify by cabin in 03.02
        marking: true #true, modify by cabin in 03.02
        max_obstacle_height: 2.0  #2.0
        min_obstacle_height: 0.0  #0.0
        # obstacle_range: 2.5
        # raytrace_range: 3.0
        #inf_is_valid: false
    #Global Filtering Paramters
    #max_obstacle_height: 0.6  #2.0
    obstacle_range: 2.5  #2.5
    raytrace_range: 3.0  #3.0

    #ObstacleCostmapPlugin
    track_unknown_space: false  # false
    footprint_clearing_enabled: true

    #VoxelCostmapPlugin
    origin_z: 0.0
    z_resolution: 0.1
    z_voxels: 10
    unknown_threshold: 10
    mark_threshold: 0
    publish_voxel_map: false
    footprint_clearing_enabled: true

global_inflation_layer:
    enabled: true 
    inflation_radius: 0.15  #0.15
    cost_scaling_factor: 10.0  #10.0

local_inflation_layer:
    enabled: true 
    inflation_radius: 0.1  #0.15
    cost_scaling_factor: 10.0  #10.0
