GlobalPlanner:
  allow_unknown: false  #default: true
  default_tolerance: 0.2  #default: 0.0
  visualize_potential: false 
  use_dijkstra: false 
  use_quadratic: true 
  use_grid_path: true 
  old_navfn_behavior: true 
  lethal_cost: 253 
  neutral_cost: 66 
  cost_factor: 0.55 
  publish_potential: true 
  orientation_mode: 0 
  orientation_window_size: 1 