local_costmap:
    #Coordinate frame and tf parameters
    global_frame: world
    robot_base_frame: global_camera_2d
    transform_tolerance: 5.0  #0.2

    #Rate parameters
    update_frequency: 5.0  #5.0
    publish_frequency: 2.0  #5.0

    #map params
    static_map: false
    rolling_window: true
    width: 6.0  #6.0
    height: 6.0  #6.0
    resolution: 0.05  #0.05
    #origin_x: 0.0  #default:0.0
    #origin_y: 0.0  #default:0.0

    #robot model
    inscribed_radius: 0.20  #0.325
    circumscribed_radius: 0.25  #0.46

    plugins:
        # - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
        - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
        # - {name: static_layer, type: "costmap_2d::StaticLayer"}
        - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}
